# USING SKLEARN NEURAL NETWORK

In [1]:
from sklearn.neural_network import MLPClassifier


reg = MLPClassifier(hidden_layer_sizes=(2,3),verbose=2,activation="relu" ,batch_size=40,random_state=1, max_iter=2000, learning_rate_init=0.03)



In [56]:
??MLPClassifier


# ON RANDOM DATASET

In [2]:
X_train = [[22,33],
           [44,55]]

y_train = [0,1]

In [3]:

reg.fit(X_train, y_train)

      

C:\Users\Admin\AppData\Roaming\Python\Python37\site-packages\sklearn\neural_network\_multilayer_perceptron.py:353: UserWarning: Got `batch_size` less than 1 or larger than sample size. It is going to be clipped
  warnings.warn("Got `batch_size` less than 1 or larger than "


Iteration 1, loss = 0.82481770
Iteration 2, loss = 0.81072171
Iteration 3, loss = 0.79776556
Iteration 4, loss = 0.78591496
Iteration 5, loss = 0.77512384
Iteration 6, loss = 0.76533503
Iteration 7, loss = 0.75648167
Iteration 8, loss = 0.74848957
Iteration 9, loss = 0.74128057
Iteration 10, loss = 0.73477665
Iteration 11, loss = 0.72890442
Iteration 12, loss = 0.72359893
Iteration 13, loss = 0.71880638
Iteration 14, loss = 0.71448509
Iteration 15, loss = 0.71005126
Iteration 16, loss = 0.69956078
Iteration 17, loss = 0.68669849
Iteration 18, loss = 0.66973401
Iteration 19, loss = 0.64899605
Iteration 20, loss = 0.62857226
Iteration 21, loss = 0.61767667
Iteration 22, loss = 0.62753616
Iteration 23, loss = 0.64651495
Iteration 24, loss = 0.64697809
Iteration 25, loss = 0.63232672
Iteration 26, loss = 0.61643039
Iteration 27, loss = 0.60760683
Iteration 28, loss = 0.60614063
Iteration 29, loss = 0.60802059
Iteration 30, loss = 0.60942583
Iteration 31, loss = 0.60823544
Iteration 32, los

MLPClassifier(batch_size=40, hidden_layer_sizes=(2, 3), learning_rate_init=0.03,
              max_iter=2000, random_state=1, verbose=2)

In [4]:
X_test =[[22,33],
           [44,55]]

y_test= [0,0]

In [8]:



y_pred=reg.predict(X_test)
y_pred
      
      

array([0, 1])

In [7]:

y_pred_prob=reg.predict_proba(X_test)
y_pred_prob

array([[9.71121293e-01, 2.88787074e-02],
       [9.97382736e-06, 9.99990026e-01]])

In [10]:

from sklearn.metrics import accuracy_score

accuracy_score(y_pred, y_test)

0.5

# USING KERAS MODELS

In [13]:
# Load dependencies

from keras.models import Sequential

from keras.layers import Dense

import numpy as np



## ON RANDOM DATASET

In [25]:
X_test =[[22.,33.],
           [44.,55.]]

X_train =[[22.,33.],
           [44.,55.]]

In [21]:
# Our vectorized labels

y_train = np.asarray(y_train).astype('float32').reshape((-1,1))
y_test = np.asarray(y_test).astype('float32').reshape((-1,1))

In [22]:
y_train

array([[0.],
       [1.]], dtype=float32)

In [11]:
# Set the input shape

input_shape = (2,)

print(f'Feature shape: {input_shape}')

Feature shape: (2,)


In [14]:
# Create the model
model = Sequential()



model.add(Dense(3, input_shape=input_shape, activation='relu'))

model.add(Dense(3, activation='relu'))

model.add(Dense(2, activation='sigmoid'))

In [ ]:
# Configure the model 

model.compile(optimizer='rmsprop',
              loss='binary_crossentropy',
              metrics=['accuracy'])

#and start training
model.fit(X_train, y_train, epochs=100, batch_size=442, verbose=1
         )

In [ ]:
#this program needs to be corrected further