# USING SKLEARN NEURAL NETWORK

In [7]:
from sklearn.neural_network import MLPRegressor, MLPClassifier


reg = MLPRegressor(hidden_layer_sizes=(2,3),verbose=2,activation="relu" ,batch_size=40,random_state=1, max_iter=2000, learning_rate_init=0.03)



In [8]:
??MLPRegressor


# ON RANDOM DATASET

In [100]:
X_train = [[22,33],
           [44,55]]

y_train = [22,34]

In [102]:

reg.fit(X_train, y_train)

      

Iteration 1, loss = 439.91277618
Iteration 2, loss = 438.17080075
Iteration 3, loss = 436.48627815
Iteration 4, loss = 434.85949119
Iteration 5, loss = 433.29007947
Iteration 6, loss = 431.77675946
Iteration 7, loss = 430.31693847
Iteration 8, loss = 428.90622148
Iteration 9, loss = 427.53787313
Iteration 10, loss = 426.20241648
Iteration 11, loss = 424.88768064
Iteration 12, loss = 423.57958647
Iteration 13, loss = 422.26361699
Iteration 14, loss = 420.92642523
Iteration 15, loss = 419.52103039
Iteration 16, loss = 417.64031843
Iteration 17, loss = 414.91432690
Iteration 18, loss = 411.11946441
Iteration 19, loss = 405.83735805
Iteration 20, loss = 398.59220824
Iteration 21, loss = 388.88394456
Iteration 22, loss = 376.21225785
Iteration 23, loss = 360.09838715
Iteration 24, loss = 340.10889393
Iteration 25, loss = 315.89219893
Iteration 26, loss = 287.23422082
Iteration 27, loss = 254.13606462
Iteration 28, loss = 216.91697632
Iteration 29, loss = 176.34701980
Iteration 30, loss = 13

C:\Users\Admin\AppData\Roaming\Python\Python37\site-packages\sklearn\neural_network\_multilayer_perceptron.py:353: UserWarning: Got `batch_size` less than 1 or larger than sample size. It is going to be clipped
  warnings.warn("Got `batch_size` less than 1 or larger than "


MLPRegressor(batch_size=40, hidden_layer_sizes=(2, 3), learning_rate_init=0.03,
             max_iter=2000, random_state=1, verbose=2)

In [103]:
X_test =[[22,33],
           [44,55]]

y_test= [22,33]

In [105]:



y_pred=reg.predict(X_test)
y_pred
      
      

array([21.97003844, 39.37681381])

In [106]:

from sklearn.metrics import r2_score

r2_score(y_pred, y_test)

0.7315827599624313

# ON DIABETES DATASET

In [108]:

from sklearn.datasets import load_diabetes

dataset = load_diabetes()
dataset.data
dataset.target

array([151.,  75., 141., 206., 135.,  97., 138.,  63., 110., 310., 101.,
        69., 179., 185., 118., 171., 166., 144.,  97., 168.,  68.,  49.,
        68., 245., 184., 202., 137.,  85., 131., 283., 129.,  59., 341.,
        87.,  65., 102., 265., 276., 252.,  90., 100.,  55.,  61.,  92.,
       259.,  53., 190., 142.,  75., 142., 155., 225.,  59., 104., 182.,
       128.,  52.,  37., 170., 170.,  61., 144.,  52., 128.,  71., 163.,
       150.,  97., 160., 178.,  48., 270., 202., 111.,  85.,  42., 170.,
       200., 252., 113., 143.,  51.,  52., 210.,  65., 141.,  55., 134.,
        42., 111.,  98., 164.,  48.,  96.,  90., 162., 150., 279.,  92.,
        83., 128., 102., 302., 198.,  95.,  53., 134., 144., 232.,  81.,
       104.,  59., 246., 297., 258., 229., 275., 281., 179., 200., 200.,
       173., 180.,  84., 121., 161.,  99., 109., 115., 268., 274., 158.,
       107.,  83., 103., 272.,  85., 280., 336., 281., 118., 317., 235.,
        60., 174., 259., 178., 128.,  96., 126., 28

In [54]:
dataset

{'data': array([[ 0.03807591,  0.05068012,  0.06169621, ..., -0.00259226,
          0.01990842, -0.01764613],
        [-0.00188202, -0.04464164, -0.05147406, ..., -0.03949338,
         -0.06832974, -0.09220405],
        [ 0.08529891,  0.05068012,  0.04445121, ..., -0.00259226,
          0.00286377, -0.02593034],
        ...,
        [ 0.04170844,  0.05068012, -0.01590626, ..., -0.01107952,
         -0.04687948,  0.01549073],
        [-0.04547248, -0.04464164,  0.03906215, ...,  0.02655962,
          0.04452837, -0.02593034],
        [-0.04547248, -0.04464164, -0.0730303 , ..., -0.03949338,
         -0.00421986,  0.00306441]]),
 'target': array([151.,  75., 141., 206., 135.,  97., 138.,  63., 110., 310., 101.,
         69., 179., 185., 118., 171., 166., 144.,  97., 168.,  68.,  49.,
         68., 245., 184., 202., 137.,  85., 131., 283., 129.,  59., 341.,
         87.,  65., 102., 265., 276., 252.,  90., 100.,  55.,  61.,  92.,
        259.,  53., 190., 142.,  75., 142., 155., 225.,  59

In [109]:
dataset.data.shape

(442, 10)

In [110]:

reg.fit(dataset.data,dataset.target)



Iteration 1, loss = 14261.73592157
Iteration 2, loss = 13841.69083599
Iteration 3, loss = 13207.64840426
Iteration 4, loss = 12210.66399938
Iteration 5, loss = 10757.22194762
Iteration 6, loss = 8798.48559890
Iteration 7, loss = 6452.41012238
Iteration 8, loss = 4287.18452799
Iteration 9, loss = 2791.67751079
Iteration 10, loss = 2226.85054686
Iteration 11, loss = 2125.21506172
Iteration 12, loss = 2072.02224204
Iteration 13, loss = 2009.84855150
Iteration 14, loss = 1957.03336715
Iteration 15, loss = 1905.02473547
Iteration 16, loss = 1883.24170264
Iteration 17, loss = 1845.68675786
Iteration 18, loss = 1812.23290522
Iteration 19, loss = 1790.32313530
Iteration 20, loss = 1763.17124737
Iteration 21, loss = 1738.47589115
Iteration 22, loss = 1711.74614917
Iteration 23, loss = 1691.86953602
Iteration 24, loss = 1670.70861356
Iteration 25, loss = 1655.62283319
Iteration 26, loss = 1642.23655975
Iteration 27, loss = 1628.36243822
Iteration 28, loss = 1623.42158308
Iteration 29, loss = 160

MLPRegressor(batch_size=40, hidden_layer_sizes=(2, 3), learning_rate_init=0.03,
             max_iter=2000, random_state=1, verbose=2)

In [111]:
reg.coefs_


#weigth matrix



[array([[-0.1162057 , -0.13600488],
        [-7.37855596, -0.1178    ],
        [14.07295837, -0.96833123],
        [ 9.47925236, -0.84401587],
        [-1.14516051,  0.07033046],
        [-3.69113787,  0.38876881],
        [-6.90107354,  0.63306544],
        [ 3.2959029 ,  0.09042091],
        [12.38212846, -0.41874271],
        [ 2.81301137, -0.67490674]]),
 array([[-4.32990874e-01,  5.74726960e+00,  7.06264621e-32],
        [-1.58035453e-30, -8.65924783e-02,  1.60186408e-30]]),
 array([[ 5.08589288e-01],
        [ 6.06367546e+00],
        [-6.20468760e-06]])]

In [113]:
#??reg.coefs_

X_test= [[ 0.03807591,.03807591,  0.05068012,  0.06169621,0.3807591 , -0.00259226,
          0.01990842, -0.01764613, 0.3807591, 0.3807591],
         
         [ 0.03807591,.03807591,  0.05068012,  0.06169621,0.3807591 , -0.00259226,
          0.01990842, -0.01764613, 0.3807591, 0.4444]
        ]


In [118]:
y_test = [300,300]

In [114]:

y_pred=reg.predict(X_test)
y_pred
      

array([363.01912703, 369.25798817])

In [119]:
  
from sklearn.metrics import r2_score

r2_score(y_pred, y_test)

-449.5301145513

# USING KERAS MODELS

In [107]:
# Load dependencies

from keras.models import Sequential

from keras.layers import Dense

import numpy as np



## ON DIABETES DATASET

In [ ]:

from sklearn.datasets import load_diabetes

dataset = load_diabetes()
dataset.data
dataset.target

In [95]:
import site
site.getsitepackages()

['C:\\ProgramData\\Anaconda3',
 'C:\\ProgramData\\Anaconda3\\lib\\site-packages']

In [120]:
# Set the input shape
input_shape = (10,)
print(f'Feature shape: {input_shape}')

Feature shape: (10,)


In [121]:
# Create the model
model = Sequential()



model.add(Dense(16, input_shape=input_shape, activation='relu'))

model.add(Dense(8, activation='relu'))

model.add(Dense(1, activation='softmax'))

In [122]:
dataset.data.shape

(442, 10)

In [5]:
a,b =1,2

a

1

In [123]:
# Configure the model 

dataset

x_train, y_train = dataset.data, dataset.target
x_test, y_test

model.compile(loss='mean_absolute_error', optimizer='adam', metrics=['mean_squared_error'])

#and start training
model.fit(x_train, y_train, epochs=100, batch_size=442, verbose=1, validation_split=0.2)




Epoch 1/100
1/1 [==============================] - 0s 384ms/step - loss: 150.4788 - mean_squared_error: 28447.5957 - val_loss: 153.7303 - val_mean_squared_error: 30054.7871
Epoch 2/100
1/1 [==============================] - 0s 56ms/step - loss: 150.4788 - mean_squared_error: 28447.5957 - val_loss: 153.7303 - val_mean_squared_error: 30054.7871
Epoch 3/100
1/1 [==============================] - 0s 88ms/step - loss: 150.4788 - mean_squared_error: 28447.5957 - val_loss: 153.7303 - val_mean_squared_error: 30054.7871
Epoch 4/100
1/1 [==============================] - 0s 45ms/step - loss: 150.4788 - mean_squared_error: 28447.5957 - val_loss: 153.7303 - val_mean_squared_error: 30054.7871
Epoch 5/100
1/1 [==============================] - 0s 48ms/step - loss: 150.4788 - mean_squared_error: 28447.5957 - val_loss: 153.7303 - val_mean_squared_error: 30054.7871
Epoch 6/100
1/1 [==============================] - 0s 40ms/step - loss: 150.4788 - mean_squared_error: 28447.5957 - val_loss: 153.7303 - va

1/1 [==============================] - 0s 48ms/step - loss: 150.4788 - mean_squared_error: 28447.5957 - val_loss: 153.7303 - val_mean_squared_error: 30054.7871
Epoch 96/100
1/1 [==============================] - 0s 48ms/step - loss: 150.4788 - mean_squared_error: 28447.5957 - val_loss: 153.7303 - val_mean_squared_error: 30054.7871
Epoch 97/100
1/1 [==============================] - 0s 40ms/step - loss: 150.4788 - mean_squared_error: 28447.5957 - val_loss: 153.7303 - val_mean_squared_error: 30054.7871
Epoch 98/100
1/1 [==============================] - 0s 48ms/step - loss: 150.4788 - mean_squared_error: 28447.5957 - val_loss: 153.7303 - val_mean_squared_error: 30054.7871
Epoch 99/100
1/1 [==============================] - 0s 48ms/step - loss: 150.4788 - mean_squared_error: 28447.5957 - val_loss: 153.7303 - val_mean_squared_error: 30054.7871
Epoch 100/100
1/1 [==============================] - 0s 48ms/step - loss: 150.4788 - mean_squared_error: 28447.5957 - val_loss: 153.7303 - val_mean_

In [124]:
model.summary()

Model: "sequential_6"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_18 (Dense)             (None, 16)                176       
_________________________________________________________________
dense_19 (Dense)             (None, 8)                 136       
_________________________________________________________________
dense_20 (Dense)             (None, 1)                 9         
Total params: 321
Trainable params: 321
Non-trainable params: 0
_________________________________________________________________


## ON CHENNAI WATER PROBLEM DATASET

In [2]:
import numpy as np

In [3]:
# Load data
dataset = np.loadtxt('chennai_reservoir_levels.csv', delimiter='|', skiprows=1, usecols=(1,2,3,4))
dataset



array([[  3.9,   0. , 268. ,   0. ],
       [  3.9,   0. , 268. ,   0. ],
       [  3.9,   0. , 267. ,   0. ],
       ...,
       [ 27. ,   0. ,   0. ,   1. ],
       [ 26. ,   0. ,   0. ,   1. ],
       [ 25. ,   0. ,   0. ,   1. ]])

In [ ]:



# Shuffle dataset
np.random.shuffle(dataset)

# Separate features and targets
X = dataset[:, 0:3]
Y = dataset[:, 3]



In [ ]:
#follow the keras process as done for diabetes dataset