# USING SKLEARN NEURAL NETWORK

In [1]:
from sklearn.neural_network import MLPClassifier


reg = MLPClassifier(hidden_layer_sizes=(2,3),verbose=2,activation="relu" ,batch_size=40,random_state=1, max_iter=2000, learning_rate_init=0.03)



In [56]:
??MLPClassifier


# ON RANDOM DATASET

In [2]:
X_train = [[22,33],
           [44,55]]

y_train = [0,1]

In [3]:

reg.fit(X_train, y_train)

      

C:\Users\Admin\AppData\Roaming\Python\Python37\site-packages\sklearn\neural_network\_multilayer_perceptron.py:353: UserWarning: Got `batch_size` less than 1 or larger than sample size. It is going to be clipped
  warnings.warn("Got `batch_size` less than 1 or larger than "


Iteration 1, loss = 0.82481770
Iteration 2, loss = 0.81072171
Iteration 3, loss = 0.79776556
Iteration 4, loss = 0.78591496
Iteration 5, loss = 0.77512384
Iteration 6, loss = 0.76533503
Iteration 7, loss = 0.75648167
Iteration 8, loss = 0.74848957
Iteration 9, loss = 0.74128057
Iteration 10, loss = 0.73477665
Iteration 11, loss = 0.72890442
Iteration 12, loss = 0.72359893
Iteration 13, loss = 0.71880638
Iteration 14, loss = 0.71448509
Iteration 15, loss = 0.71005126
Iteration 16, loss = 0.69956078
Iteration 17, loss = 0.68669849
Iteration 18, loss = 0.66973401
Iteration 19, loss = 0.64899605
Iteration 20, loss = 0.62857226
Iteration 21, loss = 0.61767667
Iteration 22, loss = 0.62753616
Iteration 23, loss = 0.64651495
Iteration 24, loss = 0.64697809
Iteration 25, loss = 0.63232672
Iteration 26, loss = 0.61643039
Iteration 27, loss = 0.60760683
Iteration 28, loss = 0.60614063
Iteration 29, loss = 0.60802059
Iteration 30, loss = 0.60942583
Iteration 31, loss = 0.60823544
Iteration 32, los

MLPClassifier(batch_size=40, hidden_layer_sizes=(2, 3), learning_rate_init=0.03,
              max_iter=2000, random_state=1, verbose=2)

In [4]:
X_test =[[22,33],
           [44,55]]

y_test= [0,0]

In [8]:



y_pred=reg.predict(X_test)
y_pred
      
      

array([0, 1])

In [7]:

y_pred_prob=reg.predict_proba(X_test)
y_pred_prob

array([[9.71121293e-01, 2.88787074e-02],
       [9.97382736e-06, 9.99990026e-01]])

In [10]:

from sklearn.metrics import accuracy_score

accuracy_score(y_pred, y_test)

0.5

# USING KERAS MODELS

In [13]:
# Load dependencies

from keras.models import Sequential

from keras.layers import Dense

import numpy as np



## ON RANDOM DATASET

In [25]:
X_test =[[22.,33.],
           [44.,55.]]

X_train =[[22.,33.],
           [44.,55.]]

In [21]:
# Our vectorized labels

y_train = np.asarray(y_train).astype('float32').reshape((-1,1))
y_test = np.asarray(y_test).astype('float32').reshape((-1,1))

In [22]:
y_train

array([[0.],
       [1.]], dtype=float32)

In [11]:
# Set the input shape

input_shape = (2,)

print(f'Feature shape: {input_shape}')

Feature shape: (2,)


In [14]:
# Create the model
model = Sequential()



model.add(Dense(3, input_shape=input_shape, activation='relu'))

model.add(Dense(3, activation='relu'))

model.add(Dense(2, activation='sigmoid'))

In [ ]:
# Configure the model 

model.compile(optimizer='rmsprop',
              loss='binary_crossentropy',
              metrics=['accuracy'])

#and start training
model.fit(X_train, y_train, epochs=100, batch_size=3, verbose=1
         )

In [ ]:
#this program needs to be corrected further

In [ ]:
#NEW DATASET

 For Each Attribute: (all numeric-valued)
   1. Number of times pregnant
   2. Plasma glucose concentration a 2 hours in an oral glucose tolerance test
   3. Diastolic blood pressure (mm Hg)
   4. Triceps skin fold thickness (mm)
   5. 2-Hour serum insulin (mu U/ml)
   6. Body mass index (weight in kg/(height in m)^2)
   7. Diabetes pedigree function
   8. Age (years)
   9. Class variable (0 or 1)

In [3]:
from numpy import loadtxt
# load the dataset

dataset = loadtxt('diabetes.csv', delimiter=',')

dataset

array([[  6.   , 148.   ,  72.   , ...,   0.627,  50.   ,   1.   ],
       [  1.   ,  85.   ,  66.   , ...,   0.351,  31.   ,   0.   ],
       [  8.   , 183.   ,  64.   , ...,   0.672,  32.   ,   1.   ],
       ...,
       [  5.   , 121.   ,  72.   , ...,   0.245,  30.   ,   0.   ],
       [  1.   , 126.   ,  60.   , ...,   0.349,  47.   ,   1.   ],
       [  1.   ,  93.   ,  70.   , ...,   0.315,  23.   ,   0.   ]])

In [21]:
import pandas as pd

pd.DataFrame(dataset).isnull().sum()


0    0
1    0
2    0
3    0
4    0
5    0
6    0
7    0
8    0
dtype: int64

In [23]:
pd.DataFrame(dataset).duplicated().sum()


0

In [ ]:
#SEABRON  ----  VIOLON PLOTS



In [24]:

X = dataset[:,0:8]

y = dataset[:,8]




In [25]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=100,test_size=0.1)


In [29]:
X_test

array([[1.000e+00, 7.900e+01, 6.000e+01, 4.200e+01, 4.800e+01, 4.350e+01,
        6.780e-01, 2.300e+01],
       [0.000e+00, 8.600e+01, 6.800e+01, 3.200e+01, 0.000e+00, 3.580e+01,
        2.380e-01, 2.500e+01],
       [5.000e+00, 1.620e+02, 1.040e+02, 0.000e+00, 0.000e+00, 3.770e+01,
        1.510e-01, 5.200e+01],
       [8.000e+00, 6.500e+01, 7.200e+01, 2.300e+01, 0.000e+00, 3.200e+01,
        6.000e-01, 4.200e+01],
       [9.000e+00, 1.230e+02, 7.000e+01, 4.400e+01, 9.400e+01, 3.310e+01,
        3.740e-01, 4.000e+01],
       [8.000e+00, 1.540e+02, 7.800e+01, 3.200e+01, 0.000e+00, 3.240e+01,
        4.430e-01, 4.500e+01],
       [1.700e+01, 1.630e+02, 7.200e+01, 4.100e+01, 1.140e+02, 4.090e+01,
        8.170e-01, 4.700e+01],
       [0.000e+00, 1.040e+02, 6.400e+01, 3.700e+01, 6.400e+01, 3.360e+01,
        5.100e-01, 2.200e+01],
       [1.000e+00, 1.960e+02, 7.600e+01, 3.600e+01, 2.490e+02, 3.650e+01,
        8.750e-01, 2.900e+01],
       [1.000e+00, 1.170e+02, 6.000e+01, 2.300e+01, 1.0

In [4]:
import numpy as np

#np.random.shuffle(dataset)
# split into input (X) and output (y) variables

#X = dataset[:,0:8]

#y = dataset[:,8]

In [ ]:

from keras.models import Sequential

from keras.layers import Dense


In [36]:
model = Sequential()

model.add(Dense(12, input_dim=8, activation='relu'))

model.add(Dense(8, activation='relu'))

model.add(Dense(1, activation='sigmoid'))


In [37]:

model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])


In [33]:
X_train.shape

(691, 8)

In [34]:
9*99

891

In [38]:
model.fit(X_train, y_train, epochs=150, batch_size=10)


Epoch 1/150
70/70 [==============================] - 0s 3ms/step - loss: 4.5344 - accuracy: 0.5745
Epoch 2/150
70/70 [==============================] - 0s 3ms/step - loss: 2.1549 - accuracy: 0.6136
Epoch 3/150
70/70 [==============================] - 0s 4ms/step - loss: 1.6734 - accuracy: 0.6266
Epoch 4/150
70/70 [==============================] - 0s 4ms/step - loss: 1.4666 - accuracy: 0.6281
Epoch 5/150
70/70 [==============================] - 0s 4ms/step - loss: 1.3443 - accuracy: 0.6368
Epoch 6/150
70/70 [==============================] - 0s 4ms/step - loss: 1.2428 - accuracy: 0.6339
Epoch 7/150
70/70 [==============================] - 0s 4ms/step - loss: 1.1452 - accuracy: 0.6440
Epoch 8/150
70/70 [==============================] - 0s 4ms/step - loss: 0.9940 - accuracy: 0.6570
Epoch 9/150
70/70 [==============================] - 0s 4ms/step - loss: 0.9096 - accuracy: 0.6729
Epoch 10/150
70/70 [==============================] - 0s 4ms/step - loss: 0.8618 - accuracy: 0.6816
Epoch 11/

70/70 [==============================] - 0s 3ms/step - loss: 0.6789 - accuracy: 0.7033
Epoch 83/150
70/70 [==============================] - 0s 3ms/step - loss: 0.5369 - accuracy: 0.7352
Epoch 84/150
70/70 [==============================] - 0s 5ms/step - loss: 0.6219 - accuracy: 0.7164
Epoch 85/150
70/70 [==============================] - 0s 5ms/step - loss: 0.5311 - accuracy: 0.7453
Epoch 86/150
70/70 [==============================] - 0s 3ms/step - loss: 0.5807 - accuracy: 0.7279
Epoch 87/150
70/70 [==============================] - 0s 4ms/step - loss: 0.5119 - accuracy: 0.7569
Epoch 88/150
70/70 [==============================] - 0s 3ms/step - loss: 0.5366 - accuracy: 0.7323
Epoch 89/150
70/70 [==============================] - 0s 4ms/step - loss: 0.5206 - accuracy: 0.7612
Epoch 90/150
70/70 [==============================] - 0s 3ms/step - loss: 0.5452 - accuracy: 0.7453
Epoch 91/150
70/70 [==============================] - 0s 4ms/step - loss: 0.5233 - accuracy: 0.7598
Epoch 92/150


In [40]:
model.summary()

Model: "sequential_2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_6 (Dense)              (None, 12)                108       
_________________________________________________________________
dense_7 (Dense)              (None, 8)                 104       
_________________________________________________________________
dense_8 (Dense)              (None, 1)                 9         
Total params: 221
Trainable params: 221
Non-trainable params: 0
_________________________________________________________________


In [ ]:
model.metrics

In [88]:
model.weights

[<tf.Variable 'dense_6/kernel:0' shape=(8, 12) dtype=float32, numpy=
 array([[ 0.49297437, -0.52554613,  0.08770722,  0.32557842, -0.58948904,
          0.21692385,  0.24219768, -0.1754069 , -0.26386562, -0.12972574,
         -0.5218681 , -0.26451132],
        [ 0.39516348, -0.17141104, -0.02938836, -0.1320113 , -0.05881833,
          0.1385266 , -0.599098  , -0.5324835 , -0.5188443 ,  0.19916062,
         -0.07421443,  0.01345397],
        [ 0.11583716,  0.0184871 ,  0.38173532,  0.39293268, -0.45759067,
          0.1393804 ,  0.2766698 , -0.4934447 , -0.4470526 , -0.25762722,
          0.00701159,  0.39033434],
        [-0.58036923, -0.2191613 , -0.45368204, -0.33606753, -0.45790532,
         -0.0474745 ,  0.39560595, -0.20544143, -0.03882898,  0.335165  ,
         -0.5286959 , -0.01077825],
        [ 0.39674592, -0.14575168, -0.3681553 ,  0.4659876 ,  0.39239046,
          0.46805596,  0.04254529,  0.15573332,  0.14347632,  0.453706  ,
         -0.3051231 ,  0.37870577],
        [ 0

In [89]:
model.variables

[<tf.Variable 'dense_6/kernel:0' shape=(8, 12) dtype=float32, numpy=
 array([[ 0.49297437, -0.52554613,  0.08770722,  0.32557842, -0.58948904,
          0.21692385,  0.24219768, -0.1754069 , -0.26386562, -0.12972574,
         -0.5218681 , -0.26451132],
        [ 0.39516348, -0.17141104, -0.02938836, -0.1320113 , -0.05881833,
          0.1385266 , -0.599098  , -0.5324835 , -0.5188443 ,  0.19916062,
         -0.07421443,  0.01345397],
        [ 0.11583716,  0.0184871 ,  0.38173532,  0.39293268, -0.45759067,
          0.1393804 ,  0.2766698 , -0.4934447 , -0.4470526 , -0.25762722,
          0.00701159,  0.39033434],
        [-0.58036923, -0.2191613 , -0.45368204, -0.33606753, -0.45790532,
         -0.0474745 ,  0.39560595, -0.20544143, -0.03882898,  0.335165  ,
         -0.5286959 , -0.01077825],
        [ 0.39674592, -0.14575168, -0.3681553 ,  0.4659876 ,  0.39239046,
          0.46805596,  0.04254529,  0.15573332,  0.14347632,  0.453706  ,
         -0.3051231 ,  0.37870577],
        [ 0

In [ ]:
model.coef_

In [44]:

# evaluate the keras model

params = model.evaluate(X_train, y_train)
print(params)


22/22 [==============================] - 0s 4ms/step - loss: 0.4698 - accuracy: 0.7771
[0.4697929322719574, 0.7771345973014832]




params = model.evaluate(X_test, y_test)
print(params)


In [ ]:
#The first is  the loss of the model on the dataset 
#the second will be the accuracy of the model on the dataset. 


In [49]:
# make probability predictions with the model
predictions = model.predict_proba(X_test)

predictions


array([[1.52719170e-01],
       [1.16562128e-01],
       [5.48266888e-01],
       [4.74363863e-02],
       [4.79474515e-01],
       [6.23420954e-01],
       [9.14917827e-01],
       [1.33643448e-01],
       [7.32638061e-01],
       [2.19296783e-01],
       [4.76775765e-02],
       [7.76343107e-01],
       [3.88120890e-01],
       [2.90808260e-01],
       [5.25072396e-01],
       [2.02248156e-01],
       [1.47298872e-01],
       [1.81227773e-01],
       [3.24797213e-01],
       [2.19233364e-01],
       [1.30481750e-01],
       [6.60552382e-02],
       [5.43033540e-01],
       [8.60041142e-01],
       [1.24785244e-01],
       [6.68473423e-01],
       [1.42964095e-01],
       [2.54770070e-01],
       [6.04653478e-01],
       [1.90072656e-01],
       [3.55865955e-02],
       [9.11951542e-01],
       [1.46858245e-01],
       [6.19812131e-01],
       [2.43143588e-01],
       [2.73396492e-01],
       [8.11488152e-01],
       [9.45186317e-02],
       [8.60029757e-02],
       [4.33039606e-01],



.152719170     ----0
.116------------0
.54-----------------1

In [14]:

# round predictions 
rounded = [round(x[0]) for x in predictions]
rounded

[1.0,
 0.0,
 1.0,
 0.0,
 1.0,
 0.0,
 0.0,
 1.0,
 1.0,
 0.0,
 0.0,
 1.0,
 0.0,
 1.0,
 1.0,
 0.0,
 0.0,
 0.0,
 1.0,
 0.0,
 0.0,
 0.0,
 1.0,
 0.0,
 1.0,
 1.0,
 1.0,
 0.0,
 0.0,
 0.0,
 0.0,
 1.0,
 0.0,
 0.0,
 1.0,
 1.0,
 1.0,
 0.0,
 0.0,
 1.0,
 0.0,
 1.0,
 0.0,
 1.0,
 1.0,
 1.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 1.0,
 1.0,
 0.0,
 1.0,
 0.0,
 1.0,
 0.0,
 0.0,
 1.0,
 0.0,
 1.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 1.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 1.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 1.0,
 0.0,
 1.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 1.0,
 0.0,
 0.0,
 0.0,
 0.0,
 1.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 1.0,
 0.0,
 0.0,
 1.0,
 1.0,
 0.0,
 0.0,
 1.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 1.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 1.0,
 1.0,
 1.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 1.0,
 0.0,
 0.0,
 1.0,
 0.0,
 0.0,
 1.0,
 0.0,
 1.0,
 1.0,
 1.0,
 1.0,
 0.0,
 0.0,
 0.0,
 1.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0

In [77]:
import numpy as np

a=[1,2,3]

b= np.array([3,3])
b

array([3, 3])

In [ ]:

print(type(a), type(b))

print(b)

In [61]:
y_test
type(y_test)

numpy.ndarray

In [62]:
type(predictions)

numpy.ndarray

In [ ]:
array([[0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0]])

In [53]:
predictions = model.predict_classes(X_test)


predictions


array([[0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0]])

In [78]:
from sklearn.metrics import confusion_matrix, accuracy_score

print(confusion_matrix(y_test, predictions))


accuracy_score(y_test, predictions)

[[42  5]
 [14 16]]


0.7532467532467533

In [83]:
pd.DataFrame(predictions).value_counts()

0    56
1    21
dtype: int64