In [21]:
#import abc

import numpy as np
import scipy as sc
#dtype('<U11')

dtype('<U11')

In [111]:

#normal list
a=[1,2,3," abc" ]
a

#array
b = np.array([1,2,"a" ,3,4])
b

#ENDIAN DTYPE
#dtype('<U11')

array(['1', '2', 'a', '3', '4'], dtype='<U11')

In [126]:
#array
arr = np.array([1,2,3,4])
type(arr)

arr.dtype

#a = np.array([1, 2, 3,4,5], ndmin = 3) 

#b = a.reshape(3,2) 


a = np.array([1, 2, 33,33,333,555,4,6]) 
print(a)
a=a.reshape(2,2,2) 

[  1   2  33  33 333 555   4   6]


array([[[  1,   2],
        [ 33,  33]],

       [[333, 555],
        [  4,   6]]])

In [175]:
a = np.arange(0,20) 
#step
b = a.reshape(4,5) 

b


array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [136]:
b = np.linspace(0,20,55)
b


array([ 0.        ,  0.37037037,  0.74074074,  1.11111111,  1.48148148,
        1.85185185,  2.22222222,  2.59259259,  2.96296296,  3.33333333,
        3.7037037 ,  4.07407407,  4.44444444,  4.81481481,  5.18518519,
        5.55555556,  5.92592593,  6.2962963 ,  6.66666667,  7.03703704,
        7.40740741,  7.77777778,  8.14814815,  8.51851852,  8.88888889,
        9.25925926,  9.62962963, 10.        , 10.37037037, 10.74074074,
       11.11111111, 11.48148148, 11.85185185, 12.22222222, 12.59259259,
       12.96296296, 13.33333333, 13.7037037 , 14.07407407, 14.44444444,
       14.81481481, 15.18518519, 15.55555556, 15.92592593, 16.2962963 ,
       16.66666667, 17.03703704, 17.40740741, 17.77777778, 18.14814815,
       18.51851852, 18.88888889, 19.25925926, 19.62962963, 20.        ])

In [174]:
#standard matrices
x1 = np.zeros((4,4), dtype = int) 

x2 = np.ones(8, dtype = int) 

x3 = np.eye(8,dtype=int) 

x4=np.identity(7,dtype=int)
x4

array([[1, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 1]])

In [164]:
x3 = np.eye(8,dtype=int) 
x3

array([[1, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 1]])

In [161]:
#pseudo code
#def identi(a,b):
 #   if type(a)==int:
  #      processing
   # if type(a)==list:
    #    throw error

import site
site.getsitepackages()

['C:\\Users\\Deepak\\anaconda33',
 'C:\\Users\\Deepak\\anaconda33\\lib\\site-packages']

In [156]:
#identi(2,3)

int

In [171]:
x = np.empty((2,2), dtype = int) 
x
arr = np.ndarray([4,3])
arr



array([4, 3])

In [195]:
#slicing indexing

a = np.arange(10,20)
print(a)
print(a[:])

print(a[::-2])


[10 11 12 13 14 15 16 17 18 19]
[10 11 12 13 14 15 16 17 18 19]
[19 17 15 13 11]


In [203]:
a = np.asarray([[1,2,3],[3,4,5],[4,5,6]]) 
print(a)  
print(1111111111)
print(a[:])

[[1 2 3]
 [3 4 5]
 [4 5 6]]
1111111111
[[1 2 3]
 [3 4 5]
 [4 5 6]]


In [224]:
a=np.array([[9., 7.],
       [5., 2.]]dtype=int)

b=np.array([[1., 9.],
       [5., 1.]], dtype=int)
print(a)
print(b)


c=np.vstack((a,b))

d=np.hstack((a,b))
d

SyntaxError: invalid syntax (<ipython-input-224-c1825538e95a>, line 2)

array([[44., 88.],
       [15., 47.]])

In [219]:
#maths

np.pi

np.sqrt(360)

print(np.floor(3.88))
print(np.ceil(3.88))





3.0
4.0
