In [20]:
#import statsmodels
import statsmodels.api as sm

import numpy as np

import pandas as pd


import os
os.getcwd()

'C:\\Users\\Deepak'

In [21]:
results2=sm.load('model.pkl')

results2.summary()

C:\Users\Deepak\anaconda33\lib\site-packages\scipy\stats\stats.py:1535: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=16
  "anyway, n=%i" % int(n))


<class 'statsmodels.iolib.summary.Summary'>
"""
                                 OLS Regression Results                                
=======================================================================================
Dep. Variable:                 TOTEMP   R-squared (uncentered):                   1.000
Model:                            OLS   Adj. R-squared (uncentered):              1.000
Method:                 Least Squares   F-statistic:                          5.719e+04
Date:                Sun, 07 Jun 2020   Prob (F-statistic):                    6.88e-24
Time:                        18:13:04   Log-Likelihood:                         -118.79
No. Observations:                  16   AIC:                                      247.6
Df Residuals:                      11   BIC:                                      251.4
Df Model:                           5                                                  
Covariance Type:            nonrobust                                                  
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
GNPDEFL       54.6161    102.007      0.535      0.603    -169.900     279.132
GNP            0.0343      0.010      3.384      0.006       0.012       0.057
UNEMP         -0.8701      0.240     -3.620      0.004      -1.399      -0.341
ARMED         -0.5552      0.287     -1.935      0.079      -1.187       0.076
YEAR          25.9330      3.043      8.521      0.000      19.234      32.632
==============================================================================
Omnibus:                        4.743   Durbin-Watson:                   0.971
Prob(Omnibus):                  0.093   Jarque-Bera (JB):                2.166
Skew:                           0.720   Prob(JB):                        0.338
Kurtosis:                       4.085   Cond. No.                     3.33e+05
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 3.33e+05. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

In [14]:
predicted=results2.predict()
predicted
#predicted.shape


array([60043.09725073, 61252.32465381, 60080.26771338, 61588.31252202,
       63661.46768773, 64182.54512854, 64787.6788836 , 63545.09110634,
       65945.90631758, 66943.78305505, 67744.17515046, 66521.56475877,
       69016.32974611, 69536.65439503, 69179.71044024, 71043.49937355])

In [22]:
results2.predict([[12,22,23,24,52], [12,22,23,422,25]])


array([1971.32918812, 1050.18080765])

In [23]:
#array/list
testdata=[[12,22,23,24,52], 
     [12,22,23,422,25]]
results2.predict(testdata)

array([1971.32918812, 1050.18080765])

In [19]:
#dataframe
df=pd.read_csv()
df.drop([0:4],axis=0)
#pd.DataFrame(arr)
results2.predict(df)



0     579.485325
1    2444.754714
dtype: float64