# Insurance data analysis

###### reading the data file


In [ ]:
import pandas as pd

path="C:\\Users\\admin\\Desktop\\Rahul\\careerera\\notebooks\\ML\\insurance.csv"

df = pd.read_csv(path)


### Online File Path - 
https://raw.githubusercontent.com/rktrojan/DataSciencePython/main/DataFiles/insurance.csv

In [3]:
import pandas as pd
#ins=0
    
def load_data(path):
    
    ins = pd.read_csv(path)
    
    print("ins --  object created")
    return ins


In [5]:
df = load_data("C:\\Users\\admin\\Desktop\\Rahul\\careerera\\notebooks\\ML\\insurance.csv")

df


ins --  object created


age     sex   bmi  children smoker     region  expenses
0      19  female  27.9         0    yes  southwest  16884.92
1      18    male  33.8         1     no  southeast   1725.55
2      28    male  33.0         3     no  southeast   4449.46
3      33    male  22.7         0     no  northwest  21984.47
4      32    male  28.9         0     no  northwest   3866.86
...   ...     ...   ...       ...    ...        ...       ...
1333   50    male  31.0         3     no  northwest  10600.55
1334   18  female  31.9         0     no  northeast   2205.98
1335   18  female  36.9         0     no  southeast   1629.83
1336   21  female  25.8         0     no  southwest   2007.95
1337   61  female  29.1         0    yes  northwest  29141.36

[1338 rows x 7 columns]

# Feature Engineering

In [6]:
df.isna().sum()

age         0
sex         0
bmi         0
children    0
smoker      0
region      0
expenses    0
dtype: int64

In [7]:
df.isnull().sum()

age         0
sex         0
bmi         0
children    0
smoker      0
region      0
expenses    0
dtype: int64

In [8]:
df[df.duplicated()]

age   sex   bmi  children smoker     region  expenses
581   19  male  30.6         0     no  northwest   1639.56

In [9]:
df[df.expenses==1639.56]

age   sex   bmi  children smoker     region  expenses
195   19  male  30.6         0     no  northwest   1639.56
581   19  male  30.6         0     no  northwest   1639.56

In [10]:
cleaned_df = df.drop_duplicates()

In [11]:
cleaned_df

age     sex   bmi  children smoker     region  expenses
0      19  female  27.9         0    yes  southwest  16884.92
1      18    male  33.8         1     no  southeast   1725.55
2      28    male  33.0         3     no  southeast   4449.46
3      33    male  22.7         0     no  northwest  21984.47
4      32    male  28.9         0     no  northwest   3866.86
...   ...     ...   ...       ...    ...        ...       ...
1333   50    male  31.0         3     no  northwest  10600.55
1334   18  female  31.9         0     no  northeast   2205.98
1335   18  female  36.9         0     no  southeast   1629.83
1336   21  female  25.8         0     no  southwest   2007.95
1337   61  female  29.1         0    yes  northwest  29141.36

[1337 rows x 7 columns]

In [12]:
cleaned_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1337 entries, 0 to 1337
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   age       1337 non-null   int64  
 1   sex       1337 non-null   object 
 2   bmi       1337 non-null   float64
 3   children  1337 non-null   int64  
 4   smoker    1337 non-null   object 
 5   region    1337 non-null   object 
 6   expenses  1337 non-null   float64
dtypes: float64(2), int64(2), object(3)
memory usage: 83.6+ KB


In [13]:
cleaned_df.corr()


age       bmi  children  expenses
age       1.000000  0.109414  0.041536  0.298308
bmi       0.109414  1.000000  0.012641  0.198637
children  0.041536  0.012641  1.000000  0.067389
expenses  0.298308  0.198637  0.067389  1.000000

# data analysis report

In [15]:
import sweetviz as sz

output = sz.analyze(cleaned_df)



                                             |                                             | [  0%]   00:00 ->…

In [16]:
output.show_html()

Report SWEETVIZ_REPORT.html was generated! NOTEBOOK/COLAB USERS: the web browser MAY not pop up, regardless, the report IS saved in your notebook/colab files.


In [17]:
cleaned_df

age     sex   bmi  children smoker     region  expenses
0      19  female  27.9         0    yes  southwest  16884.92
1      18    male  33.8         1     no  southeast   1725.55
2      28    male  33.0         3     no  southeast   4449.46
3      33    male  22.7         0     no  northwest  21984.47
4      32    male  28.9         0     no  northwest   3866.86
...   ...     ...   ...       ...    ...        ...       ...
1333   50    male  31.0         3     no  northwest  10600.55
1334   18  female  31.9         0     no  northeast   2205.98
1335   18  female  36.9         0     no  southeast   1629.83
1336   21  female  25.8         0     no  southwest   2007.95
1337   61  female  29.1         0    yes  northwest  29141.36

[1337 rows x 7 columns]

# DATA ENCODING

In [72]:

from sklearn.preprocessing import LabelEncoder, OrdinalEncoder, OneHotEncoder


le = LabelEncoder()


In [76]:
le.fit(cleaned_df.region)

le.classes_

array(['northeast', 'northwest', 'southeast', 'southwest'], dtype=object)

In [77]:
le.transform(cleaned_df.region)

array([3, 2, 2, ..., 2, 3, 1])

In [ ]:

cleaned_df["sex_enc"] = le.fit_transform(cleaned_df.sex)


In [44]:

cleaned_df["smoker_enc"] = le.fit_transform(cleaned_df.smoker)

cleaned_df["region_enc"] = le.fit_transform(cleaned_df.region)



C:\Users\admin\AppData\Local\Temp/ipykernel_16216/1894394776.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  cleaned_df["smoker_enc"] = le.fit_transform(cleaned_df.smoker)
C:\Users\admin\AppData\Local\Temp/ipykernel_16216/1894394776.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  cleaned_df["region_enc"] = le.fit_transform(cleaned_df.region)


In [65]:
cleaned_df

#forward selection

#backward selection

cleaned_df.sort_values("region")

age     sex   bmi  children smoker     region  expenses  sex_enc  \
394   46  female  32.3         2     no  northeast   9411.01        0   
282   30    male  27.6         1     no  northeast   4237.13        1   
281   54    male  40.6         3    yes  northeast  48549.18        1   
280   40  female  28.1         1    yes  northeast  22331.57        0   
942   18  female  40.2         0     no  northeast   2217.47        0   
..   ...     ...   ...       ...    ...        ...       ...      ...   
487   19    male  28.7         0     no  southwest   1253.94        1   
490   19  female  32.9         0     no  southwest   1748.77        0   
493   61    male  43.4         0     no  southwest  12574.05        1   
472   19  female  29.8         0     no  southwest   1744.47        0   
0     19  female  27.9         0    yes  southwest  16884.92        0   

     smoker_enc  region_enc  
394           0           0  
282           0           0  
281           1           0  
280           1           0  
942           0           0  
..          ...         ...  
487           0           3  
490           0           3  
493           0           3  
472           0           3  
0             1           3  

[1337 rows x 10 columns]

In [47]:
encoded_df = cleaned_df.drop(["sex","smoker","region"], axis=1) 

In [155]:
encoded_df.expenses/63770.43


0       0.264777
1       0.027059
2       0.069773
3       0.344744
4       0.060637
          ...   
1333    0.166230
1334    0.034593
1335    0.025558
1336    0.031487
1337    0.456973
Name: expenses, Length: 1337, dtype: float64

# Data Scaling


In [158]:
from sklearn.preprocessing import MinMaxScaler,MaxAbsScaler,RobustScaler,StandardScaler

??MinMaxScaler


In [147]:


ss.fit([encoded_df.age])

StandardScaler()

In [148]:
ss.transform([encoded_df.age])

array([[0., 0., 0., ..., 0., 0., 0.]])

In [150]:

display(pd.DataFrame(ss.transform([encoded_df.age])).to_string())


'   0     1     2     3     4     5     6     7     8     9     10    11    12    13    14    15    16    17    18    19    20    21    22    23    24    25    26    27    28    29    30    31    32    33    34    35    36    37    38    39    40    41    42    43    44    45    46    47    48    49    50    51    52    53    54    55    56    57    58    59    60    61    62    63    64    65    66    67    68    69    70    71    72    73    74    75    76    77    78    79    80    81    82    83    84    85    86    87    88    89    90    91    92    93    94    95    96    97    98    99    100   101   102   103   104   105   106   107   108   109   110   111   112   113   114   115   116   117   118   119   120   121   122   123   124   125   126   127   128   129   130   131   132   133   134   135   136   137   138   139   140   141   142   143   144   145   146   147   148   149   150   151   152   153   154   155   156   157   158   159   160   161   162   163   164   165   

# ML starts here

In [19]:
# data split in 2 parts - train and test

from sklearn.model_selection import train_test_split







In [49]:



train, test = train_test_split(encoded_df, test_size=.30, random_state=50)




#x_train,x_test,y_train,y_test = train_test_split(cleaned_df_x,cleaned_df_y,test_size=0.25, random_state=44)


In [50]:
train

age   bmi  children  expenses  sex_enc  smoker_enc  region_enc
852    46  35.5         0  42111.66        0           1           0
771    53  26.7         2  11150.78        0           0           3
33     63  28.3         0  13770.10        1           0           1
168    19  31.8         1   2719.28        0           0           1
830    63  33.1         0  13393.76        1           0           3
...   ...   ...       ...       ...      ...         ...         ...
229    47  25.5         2   9225.26        1           0           0
70     27  24.8         0  16577.78        0           1           2
132    53  35.9         2  11163.57        0           0           3
1314   30  23.7         3  18765.88        0           1           1
109    63  35.1         0  47055.53        1           1           2

[935 rows x 7 columns]

In [51]:
test

age   bmi  children  expenses  sex_enc  smoker_enc  region_enc
1106   49  29.9         0   8988.16        0           0           1
1268   20  33.3         0   1880.49        0           0           3
287    63  26.2         0  14256.19        0           0           1
232    19  17.8         0   1727.79        0           0           3
849    55  32.8         0  10601.63        1           0           1
...   ...   ...       ...       ...      ...         ...         ...
806    40  41.4         1  28476.73        0           0           1
1073   54  28.9         2  12096.65        0           0           0
339    46  27.7         1   8232.64        0           0           2
540    34  38.0         3   6196.45        0           0           3
69     28  24.0         3  17663.14        1           1           2

[402 rows x 7 columns]

In [52]:
train

age   bmi  children  expenses  sex_enc  smoker_enc  region_enc
852    46  35.5         0  42111.66        0           1           0
771    53  26.7         2  11150.78        0           0           3
33     63  28.3         0  13770.10        1           0           1
168    19  31.8         1   2719.28        0           0           1
830    63  33.1         0  13393.76        1           0           3
...   ...   ...       ...       ...      ...         ...         ...
229    47  25.5         2   9225.26        1           0           0
70     27  24.8         0  16577.78        0           1           2
132    53  35.9         2  11163.57        0           0           3
1314   30  23.7         3  18765.88        0           1           1
109    63  35.1         0  47055.53        1           1           2

[935 rows x 7 columns]

In [174]:
train_X = train[["age","bmi","children","sex_enc","smoker_enc","region_enc"]]

train_X

age   bmi  children  sex_enc  smoker_enc  region_enc
852    46  35.5         0        0           1           0
771    53  26.7         2        0           0           3
33     63  28.3         0        1           0           1
168    19  31.8         1        0           0           1
830    63  33.1         0        1           0           3
...   ...   ...       ...      ...         ...         ...
229    47  25.5         2        1           0           0
70     27  24.8         0        0           1           2
132    53  35.9         2        0           0           3
1314   30  23.7         3        0           1           1
109    63  35.1         0        1           1           2

[935 rows x 6 columns]

In [175]:
train_Y = train[["expenses"]]
train_Y

expenses
852   42111.66
771   11150.78
33    13770.10
168    2719.28
830   13393.76
...        ...
229    9225.26
70    16577.78
132   11163.57
1314  18765.88
109   47055.53

[935 rows x 1 columns]

In [176]:
test_X = test[["age","bmi","children","sex_enc","smoker_enc","region_enc"]]

test_X

age   bmi  children  sex_enc  smoker_enc  region_enc
1106   49  29.9         0        0           0           1
1268   20  33.3         0        0           0           3
287    63  26.2         0        0           0           1
232    19  17.8         0        0           0           3
849    55  32.8         0        1           0           1
...   ...   ...       ...      ...         ...         ...
806    40  41.4         1        0           0           1
1073   54  28.9         2        0           0           0
339    46  27.7         1        0           0           2
540    34  38.0         3        0           0           3
69     28  24.0         3        1           1           2

[402 rows x 6 columns]

In [177]:
test_Y = test[["expenses"]]
test_Y

actuals = pd.DataFrame(test_Y)

actuals.reset_index(inplace=True)

actuals.expenses

0       8988.16
1       1880.49
2      14256.19
3       1727.79
4      10601.63
         ...   
397    28476.73
398    12096.65
399     8232.64
400     6196.45
401    17663.14
Name: expenses, Length: 402, dtype: float64

# Model training phase

In [178]:
from sklearn.linear_model import  LinearRegression , Ridge, Lasso, ElasticNet

lr = LinearRegression()





from sklearn.tree import DecisionTreeClassifier, DecisionTreeRegressor

dtree=DecisionTreeClassifier()

In [179]:
#train

#le.fit(train,expenses~age+sal+gender)

lr.fit(train_X,train_Y)




LinearRegression()

In [180]:
lr.intercept_

array([-10733.30947705])

In [181]:
#slopes


lr.coef_

array([[  251.21143949,   305.46331099,   404.31804124,   -39.06118019,
        23580.05462568,  -287.05694817]])

In [182]:


lr.score(train_X,train_Y)

#training accuracy
#0.11432207502674918


0.7378099816312533


Model            ----->>> LinearRegression 


Algorithm         ----->>>  OLS and  GD 


# Model testing phase

In [183]:



predicted = lr.predict(test_X)
predicted



array([[10422.34710844],
       [ 3601.6767242 ],
       [12809.09301067],
       [-1384.21603561],
       [12776.39816707],
       [27779.70797422],
       [13687.42191782],
       [31536.53175311],
       [ 4272.59634614],
       [37187.1281181 ],
       [35081.98923246],
       [14038.30498472],
       [ 7556.19165486],
       [26689.63261063],
       [ 5107.40374802],
       [15481.47249872],
       [ 3936.37792926],
       [33639.08660897],
       [28734.5192506 ],
       [17102.31166894],
       [ 9664.13100168],
       [37953.89479836],
       [11272.40288139],
       [11380.15673187],
       [12323.43537352],
       [ 8963.61439104],
       [11992.49252171],
       [ 6020.26074297],
       [16061.75284756],
       [ 5762.93322875],
       [13102.89124168],
       [ 8248.15891499],
       [ 4913.62734832],
       [13235.71797232],
       [ 9677.53714469],
       [29684.98888685],
       [35783.18873096],
       [11739.39746023],
       [11388.63907773],
       [ 7331.16208265],


In [184]:

predictions = pd.DataFrame(predicted, columns=["expenses"])

predictions

expenses
0    10422.347108
1     3601.676724
2    12809.093011
3    -1384.216036
4    12776.398167
..            ...
397  12078.590271
398  12468.634026
399   9113.954599
400   9767.268562
401  27811.563965

[402 rows x 1 columns]

# error = actual-predicted

In [185]:


Error = test_Y - lr.predict(test_X)

Error

index      expenses
0    -9316.347108  -1434.187108
1    -2333.676724  -1721.186724
2   -12522.093011   1447.096989
3     1616.216036   3112.006036
4   -11927.398167  -2174.768167
..            ...           ...
397 -11272.590271  16398.139729
398 -11395.634026   -371.984026
399  -8774.954599   -881.314599
400  -9227.268562  -3570.818562
401 -27742.563965 -10148.423965

[402 rows x 2 columns]

In [186]:
#error analysis

actuals.expenses - predictions.expenses


0      -1434.187108
1      -1721.186724
2       1447.096989
3       3112.006036
4      -2174.768167
           ...     
397    16398.139729
398     -371.984026
399     -881.314599
400    -3570.818562
401   -10148.423965
Name: expenses, Length: 402, dtype: float64

In [187]:

#ACTUAL vs PREDICTED values
pd.concat([pd.DataFrame(actuals["expenses"]),predictions], axis=1)



expenses      expenses
0     8988.16  10422.347108
1     1880.49   3601.676724
2    14256.19  12809.093011
3     1727.79  -1384.216036
4    10601.63  12776.398167
..        ...           ...
397  28476.73  12078.590271
398  12096.65  12468.634026
399   8232.64   9113.954599
400   6196.45   9767.268562
401  17663.14  27811.563965

[402 rows x 2 columns]

# Test measurements

## error analysis

In [104]:



from sklearn.metrics import mean_absolute_error,mean_absolute_percentage_error,mean_squared_error




In [190]:
#MSE

mse= mean_squared_error(actuals.expenses, predictions.expenses)


#RMSE

import math

rmse=math.sqrt(mse)

print(mse,"  ,  ",rmse)


33339217.169493213   ,   5774.012224570815


##  accuracy analysis

In [188]:
from sklearn.metrics import accuracy_score, r2_score

# lr.score(train, y~a+b)

# lr.score(train_X,train_Y)



#print(accuracy_score(actuals.expenses, predictions.expenses))

print(r2_score(actuals.expenses, predictions.expenses))

#test accuracy



0.7777971449004453


In [189]:
# train - 73.7

# test  -- 77.6


# Conclusion - 

### This  seems to be a good model per Train vs Test accuracy but still too high RMSE


# We can try other models -- 

### RIDGE and LASSO and ELASTIC NET REGRESSION


### DECISION TREES


### RANDOM FOREST

# ------------------------------------------------------------------------------------------------------

# ADDITIONAL STUDY :::::

### FORWARD SELECTION

In [196]:
from mlxtend.feature_selection import SequentialFeatureSelector as sfs

??sfs

In [200]:

sfs1 = sfs(lr, k_features=4, forward=True, verbose=2, scoring='neg_mean_squared_error')



#scoring can have values like neg_mean_squared_error, mean_squared_error or r2

In [201]:
sfs1.fit(train_X,train_Y)


[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.0s remaining:    0.0s
[Parallel(n_jobs=1)]: Done   6 out of   6 | elapsed:    0.1s finished

[2022-07-02 17:06:08] Features: 1/4 -- score: -57010626.67979513[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.0s remaining:    0.0s
[Parallel(n_jobs=1)]: Done   5 out of   5 | elapsed:    0.0s finished

[2022-07-02 17:06:08] Features: 2/4 -- score: -42687424.27148202[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.0s remaining:    0.0s
[Parallel(n_jobs=1)]: Done   4 out of   4 | elapsed:    0.0s finished

[2022-07-02 17:06:08] Features: 3/4 -- score: -39169561.65518514[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 

SequentialFeatureSelector(estimator=LinearRegression(), k_features=4,
                          scoring='neg_mean_squared_error', verbose=2)

In [204]:

feat_names = list(sfs1.k_feature_names_)

print("Here is the list of top 4 features -- ", feat_names)



Here is the list of top 4 features --  ['age', 'bmi', 'children', 'smoker_enc']
